### ISSUE TITLE
Comparison to live-server or jspm-server?

### ISSUE THREAD

**Issue by jcrben** [piotrwitek/jspm-hmr#13]
I came across this from https://github.com/piotrwitek/react-redux-typescript-starter-kit

Why use this library rather than live-server which seems to be much widely used? Hoping it's not just a not-invented here (NIH) syndrome...

**Comment by piotrwitek** [comment]
@jcrben 
jspm-server fork of live-server is not maintained anymore and hot-reload is not working: https://github.com/geelen/jspm-server/issues/40

this library was created as a dev server for JSPM/SystemJS powered projects, using chokidar based systemjs-hot-reloader, and provide easy way to integrate working and reliable hot-reload in your project that no other dev server provides out in the wild

**Comment by piotrwitek** [comment]
I'll try to add a new section in doc explaining that in my free time as it would be usefull

**Comment by jcrben** [comment]
Thanks @piotrwitek your explanation here is good.

**Comment by jcrben** [comment]
fyi, I ended up migrating to webpack - the performance here wasn't good enough for me
