### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by ryansheehan** [piotrwitek/jspm-hmr#8]
https support would be a nice feature.  Out of the box, [react-redux-typescript-starter-kit](https://github.com/piotrwitek/react-redux-typescript-starter-kit) uses this library.  However chrome automatically redirects to https.

**Comment by piotrwitek** [comment]
@ryansheehan https auto redirect is due to security changes that was added to chrome right?

**Comment by ryansheehan** [comment]
@piotrwitek yes, I did manage to make a few code changes and got https working locally.

**Comment by piotrwitek** [comment]
@ryansheehan thanks for your contribution 🍺
